version: '3'
services:
    nginx:
        image: nginx:1.15-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ~/nginx:/etc/nginx/conf.d
            - ~/letsencrypt:/etc/letsencrypt
            - ~/www-certbot:/var/www/certbot
            - dist:/var/www/dist
            - docker_front:/var/www/front
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        depends_on:
            - app
    certbot:
        image: certbot/certbot
        volumes:
            - ~/letsencrypt:/etc/letsencrypt
            - ~/www-certbot:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        depends_on:
            - app
    app:
        image: hub.globalvirtual.world/globalvirtual.front.ui:${BUILD_REVISION}
        build:
            context: ../
            dockerfile: docker/Dockerfile
        volumes:
            - dist:/app
volumes:
    dist:
    docker_front:
        external: true